mode: development

application:
  print_info: false
  logger:
    logFilePath: "/var/embargo-logs/mng-api/"
    logOnFile: false
    logOnConsole: true
    logOnDatabase: false

database:
  mongodb:
    name: "node_starter_development"
    default_collection: "default"
    uri: "mongodb://0.0.0.0:27017/node_starter_development"
  postgres:
    user: "postgres"
    host: "0.0.0.0"
    database: "node_starter"
    password: "postgres"
    port: 5432
    idleTimeoutMillis: 5000
    connectionTimeoutMillis: 5000
    ssl:
      rejectUnauthorized: false

cors:
  allow_origin: "*"
  allow_method: ["POST"]

rate_limiter:
  windowMs: 60000
  max: 100
  standardHeaders: true
  legacyHeaders: false
