mode: development

database:
  mongodb:
    name: "node_starter"
    default_collection: "default"
    uri: "mongodb://0.0.0.0:27017/node_starter"
  postgres:
    user: "postgres"
    host: "0.0.0.0"
    database: "node_starter"
    password: "postgres"
    port: 5432
    idleTimeoutMillis: 5000
    connectionTimeoutMillis: 5000
    ssl:
      rejectUnauthorized: false

cors:
  allow_origin: "*"
  allow_method: ["POST"]

rate_limiter:
  windowMs: 60000
  max: 100
  standardHeaders: true
  legacyHeaders: false
